// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqgnanpufehztxzgnrbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xZ25hbnB1ZmVoenR4emducmJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MDc3MDAsImV4cCI6MjA3MzI4MzcwMH0.u90XxNXgRyDDicCjsbPZfAKtpy7-7kdJBPebXCmQP80";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});